const plan=[
["Lun 10","14–22",[["Al risveglio","Yogurt greco 200 g + banana + mandorle 15 g"],["12:30 · Pranzo","Pasta 90 g al pomodoro + pollo 160 g + verdure + olio EVO 10 g"],["17:30 · Lavoro","1 frutto"],["19:30 · Lavoro","Piadina integrale 80–100 g + bresaola 80 g + rucola/pomodori + formaggio fresco 30 g"],["Rientro, solo se fame","Yogurt bianco 125–150 g"]]],
["Mar 11","Riposo",[["Colazione","2 uova + pane integrale 60 g + 1 frutto"],["Pranzo","Riso basmati 90 g + tonno naturale 120 g sgocciolato + verdure + olio EVO 10 g"],["Spuntino","Yogurt greco 170 g"],["Cena","Merluzzo/nasello 200 g + patate 250 g + verdure + olio EVO 10 g"]]],
["Mer 12","14–22",[["Colazione","Latte parz. scremato 250 ml + pane integrale 60 g + marmellata 20 g"],["12:30 · Pranzo","Riso 90 g + tacchino 160 g + zucchine grigliate/in padella + olio EVO 10 g"],["Lavoro","1 frutto"],["19:30 · Lavoro","Insalatona + 2 uova + tonno 80 g + pane 70 g + olio EVO 10 g"],["Rientro, solo se fame","Yogurt"]]],
["Gio 13","14–22",[["Colazione","Yogurt greco 200 g + 1 frutto + frutta secca 15 g"],["Pranzo","Pasta 90 g al pomodoro + carne magra 160 g + verdure + olio EVO 10 g"],["Lavoro","1 frutto"],["19:30 · Lavoro","Mozzarella 125 g + pomodori + pane integrale 80 g + verdure + olio EVO 10 g"],["Rientro, solo se fame","Yogurt"]]],
["Ven 14","Riposo",[["Colazione","2 uova + pane 60 g + 1 frutto"],["Pranzo","Pasta 90 g + legumi 150 g già cotti + verdure + olio EVO 10 g"],["Spuntino","Yogurt greco 170 g + 1 frutto"],["Cena","Pollo/tacchino 180 g + patate 250 g + verdure + olio EVO 10 g"]]],
["Sab 15","22–06",[["Primo pasto","Yogurt greco 200 g + banana + mandorle 15 g"],["Pranzo","Riso 90 g + pollo 160 g + verdure + olio EVO 10 g"],["20:00 · Prima del lavoro","Pesce 180–200 g + pane 80 g + verdure + olio EVO 10 g"],["01:00–02:00","Yogurt greco 170 g + 1 frutto"],["06:30 · Solo se fame","Latte 200 ml oppure yogurt; altrimenti acqua e sonno"]]],
["Dom 16","22–06",[["Dopo il risveglio","Yogurt greco 200 g + 1 frutto + mandorle 15 g"],["Pasto principale","Pasta 90 g + tonno 120 g + pomodoro/verdure + olio EVO 10 g"],["20:00 · Prima del lavoro","Pollo/tacchino 180 g + pane 80 g + verdure + olio EVO 10 g"],["Durante la notte","Yogurt 170 g + 1 frutto"],["Rientro","Piccolo alimento solo se fame"]]]
];
const shopping={
"Carne, pesce e proteine":["Petto di pollo/tacchino · circa 900 g","Carne magra · 200 g","Merluzzo/nasello o altro pesce magro · circa 400 g","Tonno al naturale · 4–5 scatolette (circa 320 g sgocciolato)","Bresaola · 100 g","Uova · 6","Legumi cotti · 1 confezione/barattolo"],
"Latticini":["Yogurt greco/bianco naturale · circa 1,5 kg","Mozzarella · 125 g","Formaggio fresco · 1 confezione piccola","Latte parzialmente scremato · 1 litro"],
"Carboidrati":["Pasta · 500 g","Riso/basmati · 500 g","Pane integrale · circa 500 g","Piadine integrali · 1 confezione","Patate · 500–750 g"],
"Frutta e verdura":["Banane · 3–4","Frutta di stagione · 10–12 pezzi","Pomodori · circa 1 kg","Insalata/rucola · 2–3 buste o cespi","Zucchine · 4–5","Verdure miste a scelta · circa 2 kg"],
"Dispensa":["Olio extravergine d'oliva","Mandorle/frutta secca · 100 g","Passata/pomodoro per pasta · 2 confezioni","Marmellata · 1 vasetto"]
};
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.tab).classList.add('active')}));
const days=document.getElementById('days');
plan.forEach((d,i)=>{const box=document.createElement('div');box.className='day';box.innerHTML=`<div class="day-head"><h3>${d[0]}</h3><span class="shift">${d[1]}</span></div>`+d[2].map((m,j)=>`<div class="meal"><b>${m[0]}</b>${m[1]}<label class="check"><input type="checkbox" data-save="meal-${i}-${j}"> Fatto</label></div>`).join('');days.appendChild(box)});
const shop=document.getElementById('shopping');Object.entries(shopping).forEach(([g,items])=>{shop.insertAdjacentHTML('beforeend',`<div class="shop-group">${g}</div>`);items.forEach((x,i)=>shop.insertAdjacentHTML('beforeend',`<label class="check"><input type="checkbox" data-save="shop-${g}-${i}"> ${x}</label>`))});
function restoreChecks(){document.querySelectorAll('[data-save]').forEach(x=>{x.checked=localStorage.getItem(x.dataset.save)==='1';x.addEventListener('change',()=>localStorage.setItem(x.dataset.save,x.checked?'1':'0'))})}restoreChecks();
let weights=JSON.parse(localStorage.getItem('weights')||'[{"date":"2026-08-08","value":121}]');
let activities=JSON.parse(localStorage.getItem('activities')||'[]');
const wdate=document.getElementById('wdate');wdate.value=new Date().toISOString().slice(0,10);
document.getElementById('adate').value=wdate.value;
document.getElementById('addWeight').addEventListener('click',()=>{const v=+document.getElementById('wvalue').value,d=wdate.value;if(!d||!v)return;weights.push({date:d,value:v});weights.sort((a,b)=>a.date.localeCompare(b.date));localStorage.setItem('weights',JSON.stringify(weights));renderWeights()});
function renderWeights(){document.getElementById('weights').innerHTML=weights.slice().reverse().map(w=>`<div class="row"><span>${w.date.split('-').reverse().join('/')}</span><b>${w.value.toFixed(1).replace('.',',')} kg</b></div>`).join('');drawChart()}
function drawChart(){const c=document.getElementById('chart'),x=c.getContext('2d'),W=c.width,H=c.height;x.clearRect(0,0,W,H);x.strokeStyle='#334155';x.lineWidth=1;for(let i=0;i<5;i++){let y=25+i*(H-50)/4;x.beginPath();x.moveTo(35,y);x.lineTo(W-20,y);x.stroke()}if(!weights.length)return;const vals=weights.map(w=>w.value),min=Math.min(115,...vals)-1,max=Math.max(121,...vals)+1;const px=i=>35+(W-65)*(weights.length===1?.5:i/(weights.length-1));const py=v=>25+(max-v)/(max-min)*(H-50);x.strokeStyle='#22c55e';x.lineWidth=4;x.beginPath();weights.forEach((w,i)=>{i?x.lineTo(px(i),py(w.value)):x.moveTo(px(i),py(w.value))});x.stroke();x.fillStyle='#86efac';weights.forEach((w,i)=>{x.beginPath();x.arc(px(i),py(w.value),6,0,Math.PI*2);x.fill()});x.fillStyle='#94a3b8';x.font='18px system-ui';x.fillText('115 kg',40,py(115)-8)}
document.getElementById('addActivity').addEventListener('click',()=>{const d=document.getElementById('adate').value,t=document.getElementById('atype').value,m=+document.getElementById('amin').value;if(!d||!m)return;activities.push({date:d,type:t,min:m});localStorage.setItem('activities',JSON.stringify(activities));renderActivities()});
function renderActivities(){document.getElementById('activities').innerHTML=activities.slice().reverse().map(a=>`<div class="row"><span>${a.date.split('-').reverse().join('/')} · ${a.type}</span><b>${a.min} min</b></div>`).join('')}
renderWeights();renderActivities();
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js');